### ISSUE TITLE
Project scope and template format

### ISSUE THREAD

**Issue by gilmrjc** [jokeyrhyme/keep-contributing#2]
For what I understand, this project aims to be what www.keepachangelog.com is but for contribution guidelines. The main difference I see between these two projects is that a change log is independent of the tech stack of the project while the contribution guidelines are heavily coupled to it. There are many technical, architectural and workflow dependent choices to make inside a document like this and it should be stated what is the scope of this project and how many details may contain. Following this thought it's also important to make the template flexible enough to be used in the largest number of projects posible. Right now the [template](https://github.com/jokeyrhyme/keep-contributing/blob/7fcb8ed974bf413204c57925b552190364dbe406/CONTRIBUTING.md) is a bunch of rules, some of them contradictory like the following ones:

- please comment with a "+1" to help vote for issues that are important to you
- please DO NOT comment with a "+1", use the Subscribe button instead

I propose to use a more general format, using the most useful found sections in the following format:

# Contribution Guidelines

Introductory lines, welcoming new user and developers to the project. The links to the license and the Code of Conduct seem appropriate here.

## Table Of Contents

- Issues and bugs
- Feature requests
- Submitting contributions
  - Style conventions
  - Testing requirements
  - Documentation
- Additional notes
- References

---

The sections proposed are what a basic contribution guidelines would cover.

-   The **issues and bugs** section is needed because some projects have an issue template, some projects ask for a minimal bug example. Generally they ask to search for the issue before opening a new one. All this info should be here.
-   The **feature requests** section is a set of general guidelines to request new features. Some projects use a mailing list to discuss feature proposals instead of the issue tracker, some projects don't, and every project handles their scope to accept or reject feature request.
-   The **submitting contribution** section should explain the project workflow, if they use a specific branch model, and any architectural specific decision made.
-   The **style conventions** should do that, state what are the coding conventions and rules used inside the project.
-   The same applies to the **testing requirements** and **documentation** sections.

Preferably the template tells the user what to do and why, not only list a set of rules. There should be places where the project maintainer can modify to adapt it to the project and have an attribution notice at the bottom like:

## Attribution

This Contribution Guidelines is adapted from the Keep Contributing, version X.X, available at URL

---

If you have any thoughts on this I would like to hear them, and I can start working on a pull request with the changes I mentioned here

EDIT by @jokeyrhyme: I just broke the sections descriptions into a bullet list to help me read it :)

**Comment by jokeyrhyme** [comment]
@gilmrjc Woah, terrific ideas! Thanks!

> Right now the template is a bunch of rules, some of them contradictory

I initially thought it would be a good idea to include some boilerplate content that included anything that might be useful to any project, with the requirement that a user would go through the template and delete everything they didn't want

That hasn't really worked well in practice: the personal benefit of having this project was that I would have a minimum-useful CONTRIBUTING.md file in all of my other projects, and this has not happened, probably in large part due to the fiddly nature of the current template

> I propose to use a more general format

I definitely like this idea: the template should apply to 90% of projects without requiring any alteration, and that means becoming more general and dropping the contradictory / project-specific language

**Comment by jokeyrhyme** [comment]
We could move more of the project-specific or optional aspects of the template into a separate file, or even provide a handy installer script / npm package that asks questions and detects useful defaults, but that would be a nice-to-have thing for later :)

**Comment by jokeyrhyme** [comment]
A helper script thing could even detect Code of Conduct and License files and properly inject hyperlinks, etc

**Comment by jokeyrhyme** [comment]
Perhaps we can move the contradictory parts out into a separate "choices" folder?

For example, we could have **choices/issues/github-plus-one.md**:

```md
-   please comment with a "+1" to help vote for issues that are important to you
-   please DO NOT comment with a "+1", use the Subscribe button instead
```

If we keep all the contradictory options in separate choice files like this, then it shouldn't be too hard for a questionnaire to download and present these options to the user later

We can, of course, just delete them, too. That's what git history is for :)

**Comment by gilmrjc** [comment]
I would prefer if tools are kept in a separate project and only preserve a template here, just like *keep a changelog* does.
